### ISSUE TITLE
How do I disable Elasticsearch/Kibana?

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox#101]
ES/Kibana are taking up too much memory, how do I disable the services?

**Comment by bravo-kernel** [comment]
To stop the services and preventing them from starting again after a reboot:

```bash
sudo systemctl stop elasticsearch
sudo unlink /etc/service/elasticsearch

sudo sv down kibana
sudo unlink /etc/service/kibana
```

**Comment by eventrac** [comment]
Hi I tried the above commands and after running "sudo systemctl stop elasticsearch" and checking top, elastic search is still running.  Similarly, "sudo unlink /etc/service/elasticsearch" provides the message "unlink: cannot unlink '/etc/service/elasticsearch': No such file or directory"

Is this cakebox version dependent?

**Comment by bravo-kernel** [comment]
It is not cakebox dependent and since it is all basic Linux/Ubuntu, Google will be your best bet here. Closing as I cannot give support on general devops.
