### ISSUE TITLE
unable to vagrant up, download fail

### ISSUE THREAD

**Issue by hassifmohd** [alt3/cakebox#102]
While attempt to download, it will fail and below is the log

vagrant version: 2.0.4
vboxmanage --version: 5.2.10r122088

> cakebox git:(caketest) vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'cakebox' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'cakebox' (v0) for provider: virtualbox
    default: Downloading: https://alt3-aee.kxcdn.com/cakebox.box
==> default: Box download is resuming from prior download progress
/opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/downloader.rb:114:in `block in download!': undefined method `split' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/subprocess.rb:191:in `block in execute'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/subprocess.rb:180:in `each'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/subprocess.rb:180:in `execute'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/subprocess.rb:22:in `execute'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/downloader.rb:285:in `block in execute_curl'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/downloader.rb:284:in `execute_curl'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/downloader.rb:185:in `download!'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_add.rb:463:in `download'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_add.rb:338:in `block in box_add'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_add.rb:330:in `each'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_add.rb:330:in `box_add'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_add.rb:146:in `add_direct'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/box_add.rb:120:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/environment.rb:598:in `lock'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/machine.rb:188:in `action'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
➜  cakebox git:(caketest)

**Comment by fernando83** [comment]
Hi all, same issue happens to me. I've tried with several versions of vagrant, including the latest ones, 2.1.2, 2.1.0, in Ubuntu 16.04 OS. Anyone can help?

**Comment by fernando83** [comment]
Bringing machine 'ceph-node1' up with 'virtualbox' provider...
==> ceph-node1: Box 'centos7-standard' could not be found. Attempting to find and install...
    ceph-node1: Box Provider: virtualbox
    ceph-node1: Box Version: >= 0
==> ceph-node1: Box file was not detected as metadata. Adding it directly...
==> ceph-node1: Adding box 'centos7-standard' (v0) for provider: virtualbox
    ceph-node1: Downloading: https://www.dropbox.com/s/hiarmp3cdzjy94o/centos7-standard.box?dl=1
/opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/downloader.rb:114:in `block in download!': undefined method `split' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/subprocess.rb:191:in `block in execute'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/subprocess.rb:180:in `each'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/subprocess.rb:180:in `execute'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/subprocess.rb:22:in `execute'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/downloader.rb:285:in `block in execute_curl'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/util/downloader.rb:284:in `execute_curl'

**Comment by gechetspr** [comment]
If it's still relevant, updating to Vagrant version 2.2.* solved the issue.

**Comment by bravo-kernel** [comment]
@gechetspr thanks for confirming 👍
