### ISSUE TITLE
https://alt3-aee.kxcdn.com/cakebox.box is still 404

### ISSUE THREAD

**Issue by limeeugenia** [alt3/cakebox#106]
Hey @bravo-kernel!

I opened an issue on this last week and you responded very fast, thank you for that!

It's been a week-end and the https://alt3-aee.kxcdn.com/cakebox.box is still 404. Maybe there is some other problem with it, can you please have a look?

Thank you!

**Comment by bravo-kernel** [comment]
Hi, thanks for reporting this.

It seems they removed my files when the credits ran out 😱. I will see if I can get hold of a copy.

**Comment by dereuromark** [comment]
I also dont have an agnostic one anymore, the downloaded one is a Linux specific one now

Is there any way we can move forward with a fresh box of sorts?

**Comment by bravo-kernel** [comment]
With some dedication the box could be rebuild using https://github.com/alt3/cakebox-builder. That's also the place where stuff could be upgraded.

**Comment by dereuromark** [comment]
I am now exploring docker based options, as my image is now also gone, and I cannot reinstall the box anymore
Right now I am looking into https://devilbox.readthedocs.io/en/latest/features.html#unlimited-projects

I think given that the project is not maintained anymore, we can also close our tickets now.

**Comment by bravo-kernel** [comment]
Yes you are right. I will abandon the repo this weekend and put a notification on the readme.

It was more than userful in its time but new technologies have taken over.

Good luck man!
