### ISSUE TITLE
change debug to development

### ISSUE THREAD

**Issue by ceeram** [alt3/cakebox#29]
Currently cakebox can be provisioned with debug set to true. This will enable debug in console application. Composer install however is done with `--no-dev`, meaning that autoloading for tests and fixtures is never loaded.
I suggest to change debug config name to something like `develop: true/false`
If develop is true, console debug level will be set to true, composer install will be done without `--no-dev`, so that autoloading for `autoload-dev` will also be generated.
Additionally we can move things like bake and debug_kit to required-dev, so that they wont be installed and included in autoloading when installing with `develop: false`

**Comment by ceeram** [comment]
Cannot assign to myself, but already started working on this one.

**Comment by bravo-kernel** [comment]
Not to sure about this one. The ``debug`` key currently does exactly what it was intended for, turning CakePHP debug on/off.

I would prefer updating the current cakebox-console install in a way that will lead to the dev-state you describe, all ready to run tests etc. (as originally intended with optimized adoption in mind). If technically possible ofcourse.

The somewhat longer installation time is something I can live with given that it's only a one-time thing. IMHO it does not outweigh the extra key and the fact that one would have to reprovision when switching to development mode.

**Comment by ceeram** [comment]
Chaging debug value also requires reprovision, changing to develop mode isnt something that one changes frequently imo.

**Comment by ceeram** [comment]
To get cakebox in an always dev state, with only difference is debug on or off, we could achieve that easily by moving autoload-dev classes to regular autoload.

**Comment by bravo-kernel** [comment]
Or by directly editing app.php which would not go for dev-mode.

You beat me to asking "What's the harm in making dev-mode the only mode?" :wink: 

The underlying motivation is making it easy for Cake devs to jump in (to C3 as well)

**Comment by ceeram** [comment]
then why even have a debug flag/command? any dev could just change that value in app.php himself?

**Comment by bravo-kernel** [comment]
All in the light of (re)creating exact copies of your box.

**Comment by ceeram** [comment]
closing for now, untill discussion comes back
