### ISSUE TITLE
completion message only shows after provisioning

### ISSUE THREAD

**Issue by ceeram** [alt3/cakebox#33]
`Your box is ready and waiting at http://10.33.10.10` is not showing when running `vagrant up` without provisioning. 

Vagrant allows for such a message with:

`config.vm.post_up_message` available since 1.6.0:
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#160-may-6-2014

**Comment by bravo-kernel** [comment]
Ty for the compatibility check Mr. @ceeram. Implemented in #36.
