### ISSUE TITLE
Extend cakebox-intaller with box-image updates

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox#35]
A box-maintenance provisioner (bash script) needs to be included so updates to pre-installed box software like phpcs and the globale CakePHP codesniffer can be updated when needed.

Usecase examples:

+ updating version of global cakephp-codesniffer
+ adding missing PHP/Nginx modules
+ optimizing apt-cache

**Comment by bravo-kernel** [comment]
It seems it would be more efficient to extend the ``cakebox update self`` command so it will:

- updates the cakebox-console project
- all other box modifications

Combined with ``vagrant reload --provision`` this should assure a consistent box in all times.

**Comment by ceeram** [comment]
Perhaps console self-update command should become part of --provision?

2015-03-23 10:31 GMT+01:00 bravo-kernel <notifications@github.com>:

**Comment by bravo-kernel** [comment]
That would be the idea. Sounds acceptable?

**Comment by ceeram** [comment]
Sure :+1:

2015-03-23 11:24 GMT+01:00 bravo-kernel <notifications@github.com>:

**Comment by bravo-kernel** [comment]
Great, PR in the making :smiley:

**Comment by bravo-kernel** [comment]
Also see https://github.com/alt3/cakebox-console/pull/87
