### ISSUE TITLE
Add logging to bash scripts

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox#47]
The [bash scripts](https://github.com/alt3/cakebox/tree/dev/.cakebox/bash) currently do log and should ideally:
- write to /var/log/cakephp/cakebox.cli.log
- not alter log file permissions `vagrant:vagrant`

**Comment by Modicrumb** [comment]
Created a PR for this but the logs I created for these bash files are formatted differently than the existing logs (not jsonified). I kind of copy pasted a bash logger off the internet and got this going. Got it from http://www.cubicrace.com/2016/03/efficient-logging-mechnism-in-shell.html

**Comment by bravo-kernel** [comment]
Thanks for this, I will try to find some time to test this this weekend and will report back.

**Comment by bravo-kernel** [comment]
Closing in favor of #90
