### ISSUE TITLE
Trying to install laravel5

### ISSUE THREAD

**Issue by alexwebster** [alt3/cakebox#58]
I am getting 
![image 1](https://cloud.githubusercontent.com/assets/186489/8163679/aad2af36-1352-11e5-864e-ac9c98ffc255.png)
That error.  
![image 2](https://cloud.githubusercontent.com/assets/186489/8163690/c026d7d6-1352-11e5-8d80-18600803bb21.png)
It also says that I have a fatal error that the fork failed.

I was able to get cakephp 3 installed but also wanted to use laravel.

**Comment by bravo-kernel** [comment]
Thanks for reporting. It looks like the vm is running out of memory. Could it be that you are using the (default) 1GB? If so, can you try allocating 2GB to the vm and see if the error still occurs.

FYI the cakebox-code is not the cause, I just provisioned the exact same Laravel 5 app without any errors, using a 2GB vm though:

![l5-screen](https://cloud.githubusercontent.com/assets/230500/8163982/9595598c-1386-11e5-92d8-4e2e77bdd399.png)

**Comment by alexwebster** [comment]
How do I add more memory to the cakebox? I am using the default 1gb.

**Comment by bravo-kernel** [comment]
Change ``memory`` from 1024 to 2048 in your ``Cakebox.yaml`` file as described [here](https://cakebox.readthedocs.org/en/latest/usage/cakebox-yaml/#vm), then reboot your vm by running ``vagrant reload`` on your local machine.

**Comment by alexwebster** [comment]
I changed that but when I type in the vagrant command, it asks for the private key that I set up for putty. Is that what should be happening?

**Comment by bravo-kernel** [comment]
I guess you are using Windows. The console is not looking for the Putty private key but for the ``cakebox_rsa`` Open-SSH key as described here http://cakebox.readthedocs.org/en/latest/tutorials/hardening-box-authentication. Did you configure the right keys in your ``Cakebox.yaml``?

**Comment by bravo-kernel** [comment]
I might be making assumptions here... which Vagrant version are you using + did you even configure the keys as described above or... did you only create a Putty key for the connection?

**Comment by alexwebster** [comment]
I am using Vagrant 1.7.2.  I am using the cakebox_rsa.  I followed the documention and used security:
  box_public_key: /Users/your-name/.ssh/cakebox_rsa.pub
  box_private_key: /Users/your-name/.ssh/cakebox_rsa
where your-name is my computers user name

**Comment by bravo-kernel** [comment]
aha, I see, the docs should be updated, we made a change so Windows users can use ~ as well. This might not be the cause but could you change both references to:

```yaml
  box_public_key: ~/.ssh/cakebox_rsa.pub
  box_private_key: ~/.ssh/cakebox_rsa
```

**Comment by alexwebster** [comment]
I have changed those references and it still is doing the same thing.

**Comment by bravo-kernel** [comment]
are you on the #cakephp irc atm? If so, that might speed up things

**Comment by alexwebster** [comment]
I am not on the irc right now.  How will that speed things up?

**Comment by bravo-kernel** [comment]
It might help stepping through the steps, could you screenshot your boot messages?

**Comment by alexwebster** [comment]
![image 3](https://cloud.githubusercontent.com/assets/186489/8165462/93fe1a50-135e-11e5-9486-b6678bcc683a.png)

**Comment by bravo-kernel** [comment]
Your keys seem to be fine as your box is up and running. 
You should be able to connect just fine using Putty.

If you want to login using the ``vagrant ssh`` command make sure to have loaded your keys as described [here](http://cakebox.readthedocs.org/en/latest/tutorials/connecting-your-github-ssh-key/#1-load-your-ssh-agent)

**Comment by alexwebster** [comment]
I am connecting fine with putty. I am wondering why when I run the 
vagrant reload and vagrant command, it asked me for the passphrase.
I should be able to load up using pagent and should not have that issue 
anymore.  Correct?

On 6/15/2015 1:07 PM, bravo-kernel wrote:
>
> Your keys seem to be fine as your box is up and running.
> You should be able to connect just fine using Putty.
>
> If you want to login using the |vagrant ssh| command make sure to have 
> loaded your keys as described here 
> <http://cakebox.readthedocs.org/en/latest/tutorials/connecting-your-github-ssh-key/#1-load-your-ssh-agent>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alt3/cakebox/issues/58#issuecomment-112141157>.
>

-- 
<http://www.sacodesign.com/> 	

Alex Webster

alex@sacodesign.com <mailto:alex@sacodesign.com>

Saco Design, Inc. <http://www.sacodesign.com/>

207-221-3255

**Comment by bravo-kernel** [comment]
Pageant is not recognized by vagrant as described in the docs, Pageant is only recognized by Putty.
That's why you need to load the non-Putty key as described earlier if you want to use ``vagrant ssh``.

Now that you are up-and-running though.... does Laravel5 work for you now?

**Comment by alexwebster** [comment]
I have Laravel 5 installed now.  I should be able just to edit the files in the Apps folder in my cakebox folder on my c drive and it should automatically update so I can start creating my app?

**Comment by bravo-kernel** [comment]
Yes, it should.

Good to hear you're up-and-running and.. apologies for sending you on that wild (certificate) goose chase. Totally interpreted your comment the wrong way.

Spread the word !
