### ISSUE TITLE
SSL error when trying to install cakebox

### ISSUE THREAD

**Issue by matt3224** [alt3/cakebox#59]
In the git bash I get to the vagrant up command and get the following ssl error, how do I fix this so I can install. Thanks.

Here's the error:

Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

Matt@MATT-PC ~
$ git clone https://github.com/alt3/cakebox.git
Cloning into 'cakebox'...
remote: Counting objects: 1706, done.
Receiving objects:  95% emote: Total 1706 (delta 0), reused 0 (delta 0), pack-re
R
Receiving objects: 100% (1706/1706), 808.00 KiB | 595.00 KiB/s, done.
Resolving deltas: 100% (1072/1072), done.
Checking connectivity... done.

Matt@MATT-PC ~
$ cd cakebox

Matt@MATT-PC ~/cakebox (dev)
$ cp Cakebox.yaml.default Cakebox.yaml

Matt@MATT-PC ~/cakebox (dev)
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'cakebox' could not be found. Attempting to find and install...

```
default: Box Provider: virtualbox
default: Box Version: >= 0
```

==> default: Adding box 'cakebox' (v0) for provider: virtualbox
    default: Downloading: https://alt3-aee.kxcdn.com/cakebox.box
    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

Matt@MATT-PC ~/cakebox (dev)
$

**Comment by bravo-kernel** [comment]
The message is quite literal, curl can't find the CA public key on your machine. A quick google hints on a new curl version that might be causing this.

- are you on Windows?
-  if so, have you tried installing the mentioned certficate bundle inside the Git Bash?
- could you post your curl version?

**Comment by matt3224** [comment]
Hi yes, i am using windows :( sorry for being inexperienced here. How do i instal the certificate bundle? Thanks for your help my curl version is below

curl 7.41.0 (i386-pc-win32) libcurl/7.41.0 OpenSSL/0.9.8zf zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s
 rtsp smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz

**Comment by bravo-kernel** [comment]
Did you manage to solve this Matt?

**Comment by bravo-kernel** [comment]
Closing due to lack of feedback.
