### ISSUE TITLE
--source option customizations

### ISSUE THREAD

**Issue by brandonjjon** [alt3/cakebox#65]
Hi there,

I'd like to be able to use the --source option while still be able to run some customizations on the files. Is this possible? Or perhaps I can add in my own commands to the cakebox script?

Thanks

**Comment by bravo-kernel** [comment]
Way back we chose to not automate cumstomizing config files combined with the ``--source`` parameter on purpose (how can we know what to update/insert?) but... your wish is valid and could be very useful.

Maybe adding a `--post-install-shells` option to the [ApplicationShell](https://github.com/alt3/cakebox-console/blob/dev/src/Shell/ApplicationShell.php) would be the best solution:

- pointing to a relative location inside the app directory so user can place shells where they like
- supporting an array so user can execute multiple shells

Feel free to create a PR on the [cakebox-console](https://github.com/alt3/cakebox-console) project.

**Comment by bravo-kernel** [comment]
Closing due to lack of feedback.
