### ISSUE TITLE
cakebox.yaml with bitbucket

### ISSUE THREAD

**Issue by birdy247** [alt3/cakebox#66]
I am using the cakebox.yaml file to create an app with the source from a private repo on bitbucket.  The examples show how to add a private repo from github but I cannot get this to work with bitbucket.  Am I doing something wrong or is it not currently supported?

Thanks

**Comment by bravo-kernel** [comment]
Honestly, unit now... .I never heard of bitbucket but I will look into it tomorrow.

**Comment by bravo-kernel** [comment]
The bitbucket repo url is recognized and parsed as expected so this should work. Just make sure you are [SSH agent forwarding](http://cakebox.readthedocs.org/en/latest/tutorials/connecting-your-github-ssh-key/#1-load-your-ssh-agent) your bitbucket ssh key in same console where you run ``vagrant provision``
