### ISSUE TITLE
Fatal error when using --majorversion 2

### ISSUE THREAD

**Issue by verheyenkoen** [alt3/cakebox#67]
When I want to add a CakePHP 2 application I find this error in the log:

> fatal: Remote branch 2.7 not found in upstream origin

I think cakebox depends on that version branch/tag but the CakePHP maintainers renamed it or something.

**Comment by bravo-kernel** [comment]
Ok, that should not happen. I will see if I can reproduce this later today. Until then you might be able to find more details about the fail in the logs.

**Comment by verheyenkoen** [comment]
Posted full log here: https://www.zerobin.net/?2bb2e32fb2a1eed2#IbZL0IMy6/7N1T3uVW3GpJJ6o58N3NlRRDp8UzDa7hI=

**Comment by bravo-kernel** [comment]
The root cause of the issue can be found [here](https://github.com/alt3/cakebox-console/blob/dev/src/Lib/CakeboxInfo.php#L77). Feel free to sumbit a PR.

**Comment by bravo-kernel** [comment]
I believe it should target [2.x](https://github.com/cakephp/cakephp/tree/2.x).
