### ISSUE TITLE
Virtual box 5.1

### ISSUE THREAD

**Issue by birdy247** [alt3/cakebox#74]
I installed version 5.1 of virtual box and cakebox was unable to start when performing vagrant up

**Comment by bravo-kernel** [comment]
I am running 5.1 myself, albeit one of the earlier versions. I will see what happens if I update to the most recent version.

![vbox5 1](https://cloud.githubusercontent.com/assets/230500/21478062/23da592a-cb48-11e6-8449-fcebe0181333.png)

**Comment by bravo-kernel** [comment]
Works for me using latest vbox:

![image](https://cloud.githubusercontent.com/assets/230500/21478226/86065846-cb49-11e6-9bd0-585b71c9122d.png)

![image](https://cloud.githubusercontent.com/assets/230500/21478243/9ba5a3c8-cb49-11e6-8861-ffd3e4268682.png)

**Comment by bravo-kernel** [comment]
Make sure you are using the latest VBoxGuestAdditions though. Instructions found at https://github.com/alt3/cakebox/issues/73#issuecomment-257384361

**Comment by birdy247** [comment]
Ill try again and provide more details if it still doesnt work.

**Comment by bravo-kernel** [comment]
OK, I also added vagrant-vbguest plugin to the installation instructions, seems it's a must-have for new users due to the aged box image.

**Comment by birdy247** [comment]
Ok great.

Thanks :-)
