### ISSUE TITLE
cakebox application add error on linux Mint

### ISSUE THREAD

**Issue by dereuromark** [alt3/cakebox#77]
Usually 
 
    cakebox application add my-project.local 

works fine

but on linux mint and a fresh install I got
```
Shell command as root:`sudo mkdir /home/vagrant/Apps/releases.local 2>&1`
* Shelled command completed successfully
Shell command as root:`sudo chown vagrant:vagrant /home/vagrant/Apps/releases.local -R 2>&1`
* Shelled command completed successfully
Error installing application sources.
```
and

```
"@message":"Error installing application sources."
```
inside that log file.

**Comment by bravo-kernel** [comment]
Are you saying that you are running cakebox-console inside a Linux Mint and thus not inside cakebox?

**Comment by dereuromark** [comment]
No, I was only referring to the host system, as the cakebox running on a Ubuntu worked fine before.
Of course those commands are running inside the VM (or wouldnt work at all).

**Comment by bravo-kernel** [comment]
could you post the full log so we can see what happens?

**Comment by dereuromark** [comment]
Closing for now.
