### ISSUE TITLE
phpMyAdmin config issue

### ISSUE THREAD

**Issue by chris-andre** [alt3/cakebox#81]
PhpMyAdmin have been installed by following the steps, and I can log in at http://cakebox.phpmyadmin/. 

When logged in, I can view databases and tables, but when trying to view a table, I get this error:
`#1146 - Table 'phpmyadmin.pma_table_uiprefs'  doesn't exist`

At phpMyAdmin home (startpage) I see the following notices/errors:
Error: `The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. To find out why click here.`
Error: `Connection for controluser as defined in your configuration failed.`
Notice: `Your PHP MySQL library version 5.5.41 differs from your MySQL server version 5.6.22. This may cause unpredictable behavior.`
Error: `Connection for controluser as defined in your configuration failed.`

$cfg['Servers'][$i]['pmadb'] **OK**

Following $cfg is `not OK`:
* $cfg['Servers'][$i]['pmadb']
* $cfg['Servers'][$i]['relation']
* $cfg['Servers'][$i]['table_info']
* $cfg['Servers'][$i]['table_coords']
* $cfg['Servers'][$i]['pdf_pages']
* $cfg['Servers'][$i]['column_info']
* $cfg['Servers'][$i]['bookmarktable']
* $cfg['Servers'][$i]['history']
* $cfg['Servers'][$i]['designer_coords']
* $cfg['Servers'][$i]['recent']
* $cfg['Servers'][$i]['table_uiprefs']
* $cfg['Servers'][$i]['tracking']
* $cfg['Servers'][$i]['userconfig']

I have installed it on work computer and personal computer. Same issue. Setup on both machines/computer are similar.
 
My setup (personal computer):
* Windows 10
* VB 5.0.36
* Vagrant 1.9.4
* Cakebox

For now it seems like phpMyAdmin don't work out of the box. I will try to do "quick steps to setup advanced features" to see how it goes. 

>Quick steps to setup advanced features:
>* Create the needed tables with the examples/create_tables.sql.
>* Create a pma user and give access to these tables.
>* Enable advanced features in configuration file (config.inc.php), for example by starting from config.sample.inc.php.
>* Re-login to phpMyAdmin to load the updated configuration file.

**Comment by bravo-kernel** [comment]
I am sorry but I don't really support phpMyAdmin so you are on your own here. I basically added it to give users an idea/starting point, long time ago so probably broken. Feel free to PR the working instructions.

Side question, did you perform the upgrade to Ubuntu 16.04 already, it "might" be easier using modern packages.

**Comment by sjundee** [comment]
Okay. I thought you might say that. I will try to figure it out, and PR if success.

I have not upgraded Ubuntu.

**Comment by bravo-kernel** [comment]
👍

**Comment by bravo-kernel** [comment]
Closing due to lack of feedback.
