### ISSUE TITLE
Upgrade - i18n error and bad gateway

### ISSUE THREAD

**Issue by chris-andre** [alt3/cakebox#84]
Thought I'd share my experience from upgrading cakebox/vb a couple of times.

I just upgraded to Ubuntu 16.04, following the instruction inside vagrant. Upgrading VB itself went fine, but I got bad geteway on all virtual domains (vhost). Also when trying to run cakebox commands, I get exeption, not finding class Locale in vendor/cakephp/cakephp/i18n/i18n.php line 244.

Bad geteway was an issue when I was upgrading/updating cakebox last week as well. 

In both cases I have `git pull` locally in cakebox and `cakebox update self` to see if the error could be fixed.

My setup:
* Windows 10
* VB 5.0.18
* Vagrant 1.9.4

I have restored my box with `vagrant snapshop pop`. Now most works fine, but dashboard (both `http://10.33.10.10` and `http://cakebox`) still gives a bad gateway.

**Comment by dereuromark** [comment]
Check if https://github.com/alt3/cakebox/issues/87#issuecomment-368122249 resolves your issue.
Sounds like you might have a similar issue here.

**Comment by bravo-kernel** [comment]
Closing as this should be solved, #100
