### ISSUE TITLE
Error installing squizlabs code_sniffer

### ISSUE THREAD

**Issue by crayfishuk** [alt3/cakebox#88]
Fresh install of latest cakebox version on Vagrant 2.0.0 (also tried 1.9.8) under VirtualBox 5.1.30 on Windows 10 (with VBOXMANAGE set with Win8 compatibility) and VirtualFile set to 2048M RAM

Always get an error creating a cake3 application:-

```
2017-10-29 23:45:44 Debug:   =>   - Installing squizlDownloading (100%)         : Downloading (connecting...)
2017-10-29 23:45:44 Debug:   =>   [ErrorException]
2017-10-29 23:45:44 Debug:   =>   copy(/home/vagrant/.composer/cache/files/squizlabs/php_codesniffer/ed88e1fd
2017-10-29 23:45:44 Debug:   =>   c0ef8619f54c3205e01909156407e6a7.zip): failed to open stream: Permission de
2017-10-29 23:45:44 Debug:   =>   nied
2017-10-29 23:45:44 Debug:   => create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-U
RL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<packag
e>] [<directory>] [<version>]
2017-10-29 23:45:44 Error: * Shelled command exited with non-zero exit code `1`
2017-10-29 23:45:44 Error: Installation failed: Error composer installing.
Shell command as root:`sudo mkdir /home/vagrant/Apps/cake3.app 2>&1`
* Shelled command completed successfully
Shell command as root:`sudo chown vagrant:vagrant /home/vagrant/Apps/cake3.app -R 2>&1`
* Shelled command completed successfully
2017-10-29 23:45:44 Warning: Error installing application sources.
Error installing application sources.
See /var/log/cakephp/cakebox.cli.log for details.
```
I've remove vagrant machine and retried with the default Ubuntu14 install and also upgraded the box to Ubuntu16 with the script - it's always the same...

Any ideas? Workarounds?

**Comment by bravo-kernel** [comment]
There have been reports of issues with Vagrant 2.x which has not been tested properly so I would advise to stay clear of using v2 yet.

Just tested on a fresh box, upgraded to Ubuntu 16 using the same Windows 10 setup but with vagrant 1.9.1 and virtualbox 5.1.14, no issues:

![image](https://user-images.githubusercontent.com/230500/32249567-cc1b4448-be89-11e7-8bb3-037dae60c099.png)

Could you re-try using the versions above? If that solves things we can/should start adding **notes** to the readme about the max-versions.

**Comment by crayfishuk** [comment]
Bugger.  Eventually did a Windows10 reset... (Windows 1709 - Creator's Fall update) - and with Vagrant 1.9.1 and VirtualBox 5.1.14 resulted in `vagrant up` not working at all.
```
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
```
Will slowly upgrade Vagrant & VB till I find one that works and then try cakebox. Watch this space...

**Comment by bravo-kernel** [comment]
Sorry to hear, watching...

**Comment by bravo-kernel** [comment]
FWIW I'm running Windows Creator Update 1703, build 15063.674 without problems

**Comment by bravo-kernel** [comment]
@crayfishuk were you able to run cakebox before btw and... any progress?

**Comment by bravo-kernel** [comment]
Closing due to lack of feedback

**Comment by dereuromark** [comment]
Refs https://github.com/alt3/cakebox/issues/94
