### ISSUE TITLE
Upgrade with PHP7.2 installs PHP7.1 extensions

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox#91]
Hardcoded here https://github.com/alt3/cakebox/blob/dev/.cakebox/bash/ubuntu-16.sh#L115

**Comment by bravo-kernel** [comment]
Should be fixed in https://github.com/alt3/cakebox/pull/93

**Comment by bravo-kernel** [comment]
Fix tested successfully. PHP 7.2 extensions installed and the cakebox application runs again. Does however still seem to have some problems creating a new application.

![image](https://user-images.githubusercontent.com/230500/35991645-1ab7ea44-0d08-11e8-83f0-c44b7d14f5db.png)

**Comment by bravo-kernel** [comment]
# FIX FOR PERMISSION ERROR WHEN CREATING A NEW APPLICATION 

I got a permission error creating a new application. Fix by running:

```bash
sudo chown vagrant:vagrant /home/vagrant/.composer/cache/files/squizlabs -R
```

**Comment by dereuromark** [comment]
This should be documented somewhere.
