### ISSUE TITLE
Missing PHP extension or unmet dependency

### ISSUE THREAD

**Issue by kmcgowan0** [alt3/cakebox#92]
When trying to run any cakebox commands, I get the following error

`Exception: Database driver Cake\Database\Driver\Mysql cannot be used due to a missing PHP extension or unmet dependency in [/cakebox/console/vendor/cakephp/cakephp/src/Database/Connection.php, line 173]`

This is the first site I've tried to create using Cakebox, so I'm a bit of a novice. Any help would be greatly appreciated.

**Comment by bravo-kernel** [comment]
The installed PHP extensions were hardcoded to 7.1.

Fixing them as we speak, https://github.com/alt3/cakebox/issues/91.

**Comment by bravo-kernel** [comment]
@kmcgowan0 @dereuromark the fix has been done. Two options for you:

1. advized: create a new box, re-run the upgrade
2. brave: uncomment the 4 lines below and rerun the update script https://github.com/alt3/cakebox/blob/dev/.cakebox/bash/ubuntu-16.sh#L8

**Comment by bravo-kernel** [comment]
Closed through #93.
