### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by kmcgowan0** [alt3/cakebox#95]
I've followed the instructions at http://cakebox.readthedocs.io/en/latest/tutorials/creating-your-first-website/ to create my first website, and according to terminal the `Installation completed successfully`
However, when I navigate to the url in chrome I get a 'This site can’t be reached' error.

The cakebox dashboard loads fine, and the app appears in it under 'Applications', but when I click through from there I get the same error.

Any help would be greatly appreciated.

**Comment by bravo-kernel** [comment]
Have you added the name of your site to the hosts file on your local machine?

http://cakebox.readthedocs.io/en/latest/tutorials/creating-your-first-website/#3-update-your-hosts-file

**Comment by kmcgowan0** [comment]
Yes, I've updated the hosts file as it said, but no luck

**Comment by bravo-kernel** [comment]
What's the name of the app you created?

**Comment by kmcgowan0** [comment]
It's called mycake3.app

**Comment by bravo-kernel** [comment]
If you `ping mycake3.app` does it return the correct IP address?

If so, did you try closing the browser completely, that would be my last resolve.

**Comment by kmcgowan0** [comment]
Ah, I think it must be a problem with my Chrome, as it works perfectly in Firefox. Thanks for all your help.

**Comment by bravo-kernel** [comment]
np
